/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sasha SEMMA (ﾉ◕ヮ◕)ﾉ (https://sketchfab.com/pupil1983)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m2-macbook-air-model-0f725550d60140b2a8a3d389ce3a3a49
Title: M2 Macbook Air model
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

import macScene from '../assets/3D/macbook.glb';

export function Macbook({ macAnimation, position, scale, onClick }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(macScene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (macAnimation && actions[macAnimation]) {
      actions[macAnimation].play();
    }
  }, [actions, macAnimation]);

  return (
    <group ref={group} position={position} scale={scale} onClick={onClick}>
      <group name="Sketchfab_Scene">
        <group
          castShadow
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.673}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, -3, 0]}>
              <group name="display_2" position={[0.028, 0.199, -0.798]}>
                <mesh
                  name="mesh_0"
                  geometry={nodes.mesh_0.geometry}
                  material={materials.body}
                />
                <mesh
                  name="mesh_0_1"
                  geometry={nodes.mesh_0_1.geometry}
                  material={materials.shiny_body}
                />
                <mesh
                  name="mesh_0_2"
                  geometry={nodes.mesh_0_2.geometry}
                  material={materials.display_glass}
                />
                <mesh
                  name="mesh_0_3"
                  geometry={nodes.mesh_0_3.geometry}
                  material={materials.screen_BLUE}
                />
                <mesh
                  name="mesh_0_4"
                  geometry={nodes.mesh_0_4.geometry}
                  material={materials.camera_glass}
                />
                <mesh
                  name="mesh_0_5"
                  geometry={nodes.mesh_0_5.geometry}
                  material={materials.black_borders}
                />
                <mesh
                  name="mesh_0_6"
                  geometry={nodes.mesh_0_6.geometry}
                  material={materials['Material.001']}
                />
                <mesh
                  name="mesh_0_7"
                  geometry={nodes.mesh_0_7.geometry}
                  material={materials.body_smooth}
                />
              </group>
              <group
                name="midnight_3"
                position={[0.028, 0.199, -0.798]}
                scale={0.118}
              >
                <mesh
                  name="Object_13"
                  geometry={nodes.Object_13.geometry}
                  material={materials.body}
                />
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials.keys}
                />
                <mesh
                  name="Object_15"
                  geometry={nodes.Object_15.geometry}
                  material={materials.key_material}
                />
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials.key_material}
                />
                <mesh
                  name="Object_17"
                  geometry={nodes.Object_17.geometry}
                  material={materials.key_material}
                />
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials.key_material}
                />
                <mesh
                  name="Object_19"
                  geometry={nodes.Object_19.geometry}
                  material={materials.keyboard_bg}
                />
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials.body_smooth}
                />
                <mesh
                  name="Object_21"
                  geometry={nodes.Object_21.geometry}
                  material={materials.touch_id_chrome_ring}
                />
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials.rubber_pads}
                />
                <mesh
                  name="Object_23"
                  geometry={nodes.Object_23.geometry}
                  material={materials.rubber_pads}
                />
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials.usb_metal}
                />
                <mesh
                  name="Object_25"
                  geometry={nodes.Object_25.geometry}
                  material={materials.Black_plastic}
                />
              </group>
              <group
                name="midnight_blue_joint_4"
                position={[0.028, 0.199, -0.798]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.137}
              >
                <mesh
                  name="Object_27"
                  geometry={nodes.Object_27.geometry}
                  material={materials.black_borders}
                />
              </group>
              <group
                name="Cube004_5"
                position={[-1.328, 0.213, -0.011]}
                scale={0.118}
              >
                <mesh
                  name="Object_29"
                  geometry={nodes.Object_29.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube001_6"
                position={[-1.262, 0.213, 0.242]}
                scale={0.118}
              >
                <mesh
                  name="Object_31"
                  geometry={nodes.Object_31.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube002_7"
                position={[-1.134, 0.213, 0.493]}
                scale={0.118}
              >
                <mesh
                  name="Object_33"
                  geometry={nodes.Object_33.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube003_8"
                position={[-1.716, 0.213, -0.262]}
                scale={0.118}
              >
                <mesh
                  name="Object_35"
                  geometry={nodes.Object_35.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube005_9"
                position={[-1.33, 0.213, -0.514]}
                scale={0.118}
              >
                <mesh
                  name="Object_37"
                  geometry={nodes.Object_37.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube006_10"
                position={[-1.635, 0.213, -0.515]}
                scale={0.118}
              >
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube007_11"
                position={[-1.634, 0.213, -0.009]}
                scale={0.118}
              >
                <mesh
                  name="Object_41"
                  geometry={nodes.Object_41.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube008_12"
                position={[-1.637, 0.213, 0.239]}
                scale={0.118}
              >
                <mesh
                  name="Object_43"
                  geometry={nodes.Object_43.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube009_13"
                position={[-1.638, 0.213, 0.494]}
                scale={0.118}
              >
                <mesh
                  name="Object_45"
                  geometry={nodes.Object_45.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube010_14"
                position={[-0.862, 0.213, 0.745]}
                scale={0.118}
              >
                <mesh
                  name="Object_47"
                  geometry={nodes.Object_47.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube011_15"
                position={[-0.538, 0.213, 0.745]}
                scale={0.118}
              >
                <mesh
                  name="Object_49"
                  geometry={nodes.Object_49.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube012_16"
                position={[0.757, 0.213, 0.745]}
                scale={0.118}
              >
                <mesh
                  name="Object_51"
                  geometry={nodes.Object_51.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube013_17"
                position={[0.998, 0.213, 0.744]}
                scale={0.118}
              >
                <mesh
                  name="Object_53"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube015_18"
                position={[1.579, 0.213, 0.241]}
                scale={0.118}
              >
                <mesh
                  name="Object_55"
                  geometry={nodes.Object_55.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube016_19"
                position={[1.645, 0.213, -0.264]}
                scale={0.118}
              >
                <mesh
                  name="Object_57"
                  geometry={nodes.Object_57.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube017_20"
                position={[-1.715, 0.213, 0.744]}
                scale={0.118}
              >
                <mesh
                  name="Object_59"
                  geometry={nodes.Object_59.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube018_21"
                position={[-1.457, 0.213, 0.744]}
                scale={0.118}
              >
                <mesh
                  name="Object_61"
                  geometry={nodes.Object_61.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube019_22"
                position={[-1.198, 0.213, 0.744]}
                scale={0.118}
              >
                <mesh
                  name="Object_63"
                  geometry={nodes.Object_63.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube020_23"
                position={[1.257, 0.213, 0.744]}
                scale={0.118}
              >
                <mesh
                  name="Object_65"
                  geometry={nodes.Object_65.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube021_24"
                position={[1.774, 0.213, 0.744]}
                scale={0.118}
              >
                <mesh
                  name="Object_67"
                  geometry={nodes.Object_67.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube022_25"
                position={[1.514, 0.213, 0.635]}
                scale={0.118}
              >
                <mesh
                  name="Object_69"
                  geometry={nodes.Object_69.geometry}
                  material={materials.material_0}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/macbook.glb');
